<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <OutputType>Exe</OutputType>
    <IsPublishable>false</IsPublishable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Moq.AutoMock" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VsTestToMtp\VsTestToMtp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Moq.AutoMock" />
  </ItemGroup>
</Project>
